---
outlines:
    default:       { width:  48.0, height: 40 }
    shift:         { width:  50.0, height: 40 }
    show-numbers:  { width:  60.0, height: 40 }
    spacebar:      { width: 280.0, height: 40 }
    preferences:   { width:  35.0, height: 40 }
    return:        { width:  94.0, height: 40 }
    backspace:     { width:  56.0, height: 40 }
    secondary-key: { width:  32.0, height: 40 }
    spacer:        { width:   4.0, height: 40 }

views:
    base:
        - "sp q w e r t y u i o p sp sp BackSpace sp"
        - "sp sp sp a s d f g h j k l sp sp sp sp sp sp sp sp sp sp sp left_arrow right_arrow"
        - "show_upper z x c v b n m sp sp sp sp dash underbar slash at dot sp sp"
        - "show_numbers preferences sp sp sp sp space sp sp sp sp return sp sp"
    upper:
        - "sp Q W E R T Y U I O P sp sp BackSpace sp"
        - "sp sp sp A S D F G H J K L sp sp sp sp sp sp sp sp sp sp sp left_arrow right_arrow"
        - "show_upper Z X C V B N M sp sp sp sp dash underbar slash at dot sp sp"
        - "show_numbers preferences sp sp sp sp space sp sp sp sp return sp sp"
    numbers:
        - "sp 1 2 3 4 5 6 7 8 9 0 sp sp sp BackSpace"
        - "sp sp sp @ # $ % & - _ + ( ) sp sp left_arrow right_arrow"
        - "show_symbols , \" ' : ; ! ? sp sp sp sp dash underbar slash at dot sp sp"
        - "show_letters preferences sp sp sp sp space sp sp sp sp return sp sp"
    symbols:
        - "sp ~ ` | · √ π τ ÷ × ¶ sp sp BackSpace"
        - "sp sp sp © ® £ € ¥ ^ ° * { } sp sp left_arrow right_arrow"
        - "show_numbers_from_symbols \\ / < > = [ ]"
        - "show_letters preferences sp sp sp sp space sp sp sp sp return sp sp"

buttons:
    show_upper:
        action:
            locking:
                lock_view: "upper"
                unlock_view: "base"
        outline: "shift"
        icon: "key-shift"
    BackSpace:
        outline: "backspace"
        icon: "edit-clear-symbolic"
        action: "erase"
    # The world
    preferences:
        action: "show_prefs"
        outline: "preferences"
        icon: "keyboard-mode-symbolic"
    show_numbers:
        action:
            set_view: "numbers"
        outline: "show-numbers"
        label: "123"
    show_numbers_from_symbols:
        action:
            set_view: "numbers"
        outline: "show-numbers"
        label: "123"
    show_letters:
        action:
            set_view: "base"
        outline: "show-numbers"
        label: "ABC"
    show_symbols:
        action:
            set_view: "symbols"
        outline: "show-numbers"
        label: "*/="
    space:
        outline: "spacebar"
        text: " "
    return:
        outline: "return"
        icon: "key-enter"
        keysym: "Return"
    up_arrow:
        outline: "secondary-key"
        label: "↑"
        keysym: "Up"
    down_arrow:
        outline: "secondary-key"
        label: "↓"
        keysym: "Down"
    left_arrow:
        outline: "secondary-key"
        label: "←"
        keysym: "Left"
    right_arrow:
        outline: "secondary-key"
        label: "→"
        keysym: "Right"
    at:
        outline: "secondary-key"
        text: "@"
    dot:
        outline: "secondary-key"
        text: "."
    underbar:
        outline: "secondary-key"
        text: "_"
    dash:
        outline: "secondary-key"
        text: "-"
    slash:
        outline: "secondary-key"
        text: "/"
    sp:
        outline: "spacer"
        text: ""
